require("custom.remap")
require("custom.telescope")
require("custom.statusline")
require("custom.comment")
require("custom.dap")
require("custom.rt")
require("custom.options")
require("toggleterm").setup()
require("symbols-outline").setup()
require("git-conflict").setup()
require("catppuccin").setup({
    transparent_background = true,
})
require("custom.snippets")
require("custom.devicons")
require("custom.nvim-tree")
require("custom.barbar")
